#!/bin/sh

bucket=com.bigdata.rpxml.dev
file=/tmp/$1

if [ ! -f "$file" ]
then
    aws s3 cp "s3://$bucket/$1" $file
fi

if [ -f "$file" ]
then
    if [ ! -f "$file.pretty.xml" ]
    then
        xmllint $file --format --output $file.pretty.xml
    fi

    $EDITOR $file.pretty.xml
fi

