session_name: base
# start_directory: ./ # load session relative to config location (project root).
# before_script: ./.tmuxp-before-script.sh
start_directory: ~/ # load session relative to config location (project root).
# shell_command_before:
# - '[ -f .venv/bin/activate ] && source .venv/bin/activate && reset'
windows:
- window_name: base
  focus: True
  layout: tiled
  panes:
  - startvpn
  - read && yay -Syuu
- window_name: code
  layout: main-horizontal
  start_directory: ~/code/
  panes:
  - vim
#  - make serve
#  - make SPHINXBUILD='poetry run sphinx-build' watch
