#!/usr/bin/env python3

import sys
import awsso


def copy_profile(argv):
    if len(argv) != 2:
        print("Usage:")
        print("\t {} cp <from> <to>".format(argv[0]))
        return False
    awsso.copy_profile(argv[0], argv[1] or 'default')


def ls_profiles(argv):
    print('\n'.join(awsso.list_profiles()))


def main():
    argv = sys.argv[1:]
    if len(argv) == 0:
        print("Usage:")
        print("\t {} <command>".format(sys.argv[0]))
        return False
    command = argv[0]

    commands = {
        'cp': copy_profile,
        'ls': ls_profiles,
    }
    if command in commands:
        return commands[command](argv[1:])
    else:
        print('{} not supported'.format(command))
        print('The command must be one of [{}]'.format(
            ', '.join(commands.keys())
        ))
        return False


if __name__ == '__main__':
    if main() is False:
        sys.exit(1)
