#!/usr/bin/env python3

import webbrowser
import sys


def main():
    base = 'https://jira.ravenpack.com/'
    if len(sys.argv) == 2:
        issue = 'BIG-{}'.format(sys.argv[1])
        url = '{}/browse/{}'.format(base, issue)
    else:
        url = base
    webbrowser.open(url)

if __name__ == '__main__':
    main()
