#!/bin/bash

list() {
    echo "${1}i3"
    echo "${1}qtile"
    echo "${1}bar"
    echo "${1}nvim"
    echo "${1}vim-plugins"
    echo "${1}zsh"
    echo "${1}xresources"
    echo "${1}config"
    echo "${1}tmux"
    echo "${1}tmuxp"
    echo "${1}task"
    echo "${1}aws"
    echo "${1}notif"
    echo "${1}alacritty"
    echo "${1}ssh"
    echo "${1}rmpc"
}

if [ "$#" -ne 1 ]; then
    pushd ~/.config
    fzf | xargs -I {} $EDITOR {}
    popd 
    # echo "Wrong number of arguments. Usage:"
    # echo ""
    # echo "  config SOMETHING"
    # echo ""
    # echo "Where SOMETHING can be:"
    # list " -> "
    # exit
fi


case $1 in
    ls)
        list
    ;;
    i3)
        cd ~/.config/i3/ && $EDITOR config
    ;;
    qtile)
        cd ~/.config/qtile/ && $EDITOR config.py
    ;;
    bar)
        $EDITOR ~/.config/i3blocks/config
    ;;
    nvim)
        $EDITOR ~/.config/nvim/init.vim
    ;;
    vim-plugins)
        $EDITOR ~/.vim/plugins.vim
    ;;
    zsh)
        $EDITOR ~/.zshrc
    ;;
    xresources)
        $EDITOR ~/.Xresources && xrdb ~/.Xresources
    ;;
    config)
        $EDITOR ~/scripts/config
    ;;
    tmux)
        $EDITOR ~/.tmux.conf
    ;;
    tmuxp)
        $EDITOR ~/.config/tmuxp/
    ;;
    task)
        $EDITOR ~/.taskrc
    ;;
    aws)
        $EDITOR ~/.aws/credentials
    ;;
    stuff)
        cd ~/Code/config-files
    ;;
    notif)
        $EDITOR ~/.config/dunst/dunstrc
    ;;
    alacritty)
        $EDITOR ~/.config/alacritty/alacritty.toml
    ;;
    ssh)
        $EDITOR ~/.ssh/config
    ;;
    rmpc)
        $EDITOR ~/.config/rmpc/config.ron
    ;;
    shortlist)
        echo i3 nvim vim-plugins zsh xresources tmux stuff config
    ;;
    *)
        echo "I don't know how to config $1"
    ;;

esac
