#!/bin/bash

#ARGUMENTS=$(slop --format="--x=%x --y=%y --width=%w --height=%h") || exit -1
#rect=`slop --format="--x=%x --y=%y --width=%w --height=%h"` 
#byzanz-record --duration=10 $rect ~/Pictures/byzanz.gif

# Delay before starting
DELAY=2
FILE=/tmp/recorded.gif

# Sound notification to let one know when recording is about to start (and ends)
beep() {
    paplay /usr/share/sounds/KDE-Im-Irc-Event.ogg &
}

# xrectsel from https://github.com/lolilolicon/xrectsel
#ARGUMENTS=$(xrectsel "--x=%x --y=%y --width=%w --height=%h") || exit -1
slop=$(slop -n -f "%x %y %w %h %g %i") || exit -1
read -r X Y W H G ID < <(echo $slop)
BYZANZ_ARGUMENTS="--x=$X --y=$Y --width=$W --height=$H"
SCREENKEY_ARGUMENTS="-g $G"


# Duration and output file
if [ $# -gt 0 ]; then
    D="--duration=$@"
else
    echo Default recording duration 10s to $FILE
    #echo Default recording duration 10s to /Pictures/gifshot-/$(date +%F_%R).gif
    #D="--duration=15 /tmp/recorded.gif"
    D="--exec=xclock $FILE"
    #D="--duration=10 \"$HOME/Pictures/gifshot-$(date +%F_%R).gif\""
fi

echo Delaying $DELAY seconds. After that, byzanz will start
for (( i=$DELAY; i>0; --i )) ; do
    echo $i
    sleep 1
done
#beep
#echo byzanz-record --verbose --delay=0 ${BYZANZ_ARGUMENTS} $D
screenkey -g "$G" &
byzanz-record ${BYZANZ_ARGUMENTS} $D
killall screenkey
sxiv -a $FILE
dragon-drop $FILE

#beep
