#!/bin/bash

gitmoji=/home/jose/.nvm/versions/node/v11.14.0/bin/gitmoji

$gitmoji -l \
    | dmenu -i -l 10 \
    | awk '{print $3}' \
    | tr -d "\n" \
    | xsel --clipboard --input # ~/Scripts/copy
