#!/usr/bin/bash

set -e

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <zipfile> <destination>"
    exit 1
fi

unzip $1 -d $2
sudo mv "$2" "/usr/share/fonts/$2"
fc-cache -vf > /dev/null
echo "Fonts installed successfully to /usr/share/fonts/$2"
