#!/usr/bin/zsh

JIRA_SERVER_PATTERN='^(RSP|RPA|TOOL|MNT)-[0-9]+'
JIRA_CLOUD_PATTERN='^(DS|CLD|SA|TWOS|ET)-[0-9]+'
JIRA_SERVER_URL="https://jira.ravenpack.com"
JIRA_CLOUD_URL="https://ravenpack.atlassian.net"

# Open a Jira by code.
open_command () {
	emulate -L zsh
	setopt shwordsplit
	local open_cmd
	case "$OSTYPE" in
		(darwin*) open_cmd='open'  ;;
		(cygwin*) open_cmd='cygstart'  ;;
		(linux*) open_cmd='xdg-open'  ;;
		(msys*) open_cmd='start ""'  ;;
		(*) echo "Platform $OSTYPE not supported"
			return 1 ;;
	esac
	if [[ "$OSTYPE" = darwin* ]]
	then
		$open_cmd "$@" &> /dev/null
	else
		nohup $open_cmd "$@" &> /dev/null
	fi
}
if [ $# -eq 0 ]
then
    echo "Usage:"
    echo "    jira CODE"
    exit -1
fi

RECENT_JIRAS=~/jiras.txt

JIRA=$1
NAMED_JIRA=$(jira-get code,summary code=$JIRA separator=" ")
# Save jira
echo "$NAMED_JIRA\n$( cat $RECENT_JIRAS )" | awk '!x[$0]++' > $RECENT_JIRAS

# Go to destkop 7
#i3-msg workspace '7: '

echo "Opening jira $JIRA"
if echo "$JIRA" | grep -oE "$JIRA_CLOUD_PATTERN" > /dev/null; then
    echo "Using Jira cloud"
    JIRA_URL=$JIRA_CLOUD_URL
else
    echo "Using Jira server"
    JIRA_URL=$JIRA_SERVER_URL
fi


# open 
open_command "$JIRA_URL/browse/$JIRA"
