#!/usr/bin/env bash

SRC=/home/jose/git/jira

# Activate environment
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

pyenv activate teamstats 1>/dev/null 2>&1

/usr/bin/env python $SRC/jira.py "$@"

# Deactivate environment
pyenv deactivate
