#!/usr/bin/env bash

RECENT_JIRAS=~/jiras.txt

# Get a jira code from the saved ones or a new one
selected_jira=$(cat $RECENT_JIRAS | dmenu -i -l 10)

# If the user enters a number, assume BIG project
re='^[0-9]+$'
if [[ $selected_jira =~ $re ]] ; then
    selected_jira=BIG-$selected_jira
fi
echo Opening $selected_jira

# Open the jira code
echo $selected_jira | awk '{print $1}' | xargs jira-open
