#!/usr/bin/env bash
DMENU="${DMENU:-dmenu}"
DIR=~/Pictures/memes/

find $DIR* -printf "%f\n" \
    | $DMENU -l 5 \
    | awk "{print \"$DIR\"\$1}" \
    | xargs dragon
    #| xclip -i -selection clipboard -t text/uri-list

