#!/usr/bin/bash

function all {
    tmuxp load -d \
        base \
        smart-topics-master \
    # Disabled
    #   cdk \
    #   daily-validation \
    #   webapps \
    #   dumpy \
    #   st-auth-webhook-notifications-ddb-stream \
    #   st-subscriptions \
    #   st-subscriptions-dispatcher \
    #   st-subscriptions-event-processor \
    #   subscriptionslib \
    #   dumpy-api \
    #   python-api \
    #   dataset-api \
    #   entitytool \
    #   pysync \
    #   bigdata-client \
    #   monitoring-proxy \
    #   st-profiles \
    #   bdsm \
    tmux attach -t base
}

parse_args() {
    echo $1
    case "$1" in
        all)
             all
             ;;
         '')
             opt=$(tmuxp ls | grep '^  ' | sed 's/ //g' | fzf)
             [[ -z "$opt" ]] || tmuxp load "$opt"
             ;;
         *)
             opt=$(tmuxp ls | grep '^  ' | grep "$1" | sed 's/ //g' | fzf)
             [[ -z "$opt" ]] || tmuxp load "$opt"
             ;;
    esac
}

parse_args $@
