#!/usr/bin/env bash

function all {
    tmuxp load -d base \
        webapps \
        dumpy \
        cdk \
        smart-topics \
        subscriptions \
        subscriptions-dispatcher \
        subscriptions-event-processor
    # Disabled
    #   dumpy-api \
    #   python-api \
    #   dataset-api \
    #   entitytool \
    #   pysync \
    #   bigdata-client \
    #   monitoring-proxy \
    #   bdsm \
    tmux attach -t base
}

parse_args() {
    echo $1
    case "$1" in
        all)
             all
             ;;
         '')
             opt=$(tmuxp ls | fzf)
             [[ -z "$opt" ]] || tmuxp load "$opt"
             ;;
         *)
             opt=$(tmuxp ls | grep "$1" | fzf)
             [[ -z "$opt" ]] || tmuxp load "$opt"
             ;;
    esac
}

parse_args $@
