#!/usr/bin/env bash

function all {
    tmuxp load -d base
    # tmuxp load -d entitytool
    tmuxp load -d webapps
    # tmuxp load -d pysync
    tmuxp load -d dumpy
    tmuxp load -d dumpy-api
    tmuxp load -d python-api
    # tmuxp load -d bigdata-client
    #tmuxp load -d monitoring-proxy
    # tmuxp load -d cdk
    tmux attach -t base
}

parse_args() {
    echo $1
    case "$1" in
        all)
             all
             ;;
         '')
             opt=$(tmuxp ls | fzf)
             [[ -z "$opt" ]] || tmuxp load "$opt"
             ;;
         *)
             opt=$(tmuxp ls | grep "$1" | fzf)
             [[ -z "$opt" ]] || tmuxp load "$opt"
             ;;
    esac
}

parse_args $@
