#!/usr/bin/env bash

function base {
    cd ~
    tmuxp load -d base
}

function entitytool {
    cd ~/git/python/entitytool
    tmuxp load -d entitytool
}

function webapps {
    cd ~/git/python/webapps
    tmuxp load -d webapps
}

function pysync {
    cd ~/git/python/pysync
    tmuxp load -d pysync
}

function dumpy {
    cd ~/git/python/dumpy
    tmuxp load -d dumpy
}

function all {
    base
    entitytool
    webapps
    pysync
    dumpy
    tmux attach -t base
}

all
