#!/usr/bin/bash

pass otp -c okta-totp
icon=/usr/share/icons/Papirus-Dark/16x16/emblems/emblem-encrypted-locked.svg
notify-send \
    -r  1000 \
    -i $icon \
    -t 10000 \
    "Okta TOTP" \
    "Your OTP has been copied to the clipboard." \
