#!/usr/bin/bash
mr=$(glab mr list | fzf)
mr_id=$(echo $mr | sed 's/!\(.[0-9]*\).*/\1/')
branch=$(echo $mr | sed 's/.* ← (\(.*\))/\1/')

rootdir=$(git rev-parse --show-toplevel)
project_name=$(basename "$rootdir")

echo MR $mr_id
echo branch $branch

worktreedir="$rootdir/../$project_name-forest/$mr_id-$branch"

git fetch
git worktree add "$worktreedir" "$branch"

TMUX_SESSION="$project_name-$mr_id"

function create_session {
    tmux has-session -t "$1"
    if [ $? != 0 ]
    then
        TMUX= tmux new -s "$1" -d -c "$worktreedir"
    fi
    tmux attach -t "$1"

    tmux new-window -t "$1:1" -n Description -S -c "$worktreedir"
    tmux new-window -t "$1:2" -n Description -S -c "$worktreedir"
}

function run {
    tmux send -t "$TMUX_SESSION:$1" "$2" ENTER
}

create_session "$TMUX_SESSION"

run 1 "git pull"
run 1 "mrvim"
run 2 "glab mr show"
tmux switch-client -t $"$TMUX_SESSION"
