#!/bin/bash

OPTION=$(echo 'Select AWS profile
Deploy
Config
Gif rec
Meme selector
ASCII ART
Edit script' | dmenu -i -l 10)

notify() {
    notify-send -a Script $1 -u normal
}

case $OPTION in
    "Select AWS profile")
        aws-select
    ;;
    "Deploy")
        deploy ls | dmenu | xargs -I {} deploy "{}" | xargs -I {} notify-send -a Script "{}"
    ;;
    "Config")
        EDITOR=editi3 config $(config ls | dmenu -i -l 10)
    ;;
    "Gif rec")
        gifrec
    ;;
    "Meme selector")
        memesel
    ;;
    "ASCII ART")
        cat ~/Documents/ascii-art.txt | dmenu -l 10 | xsel --clipboard --input
    ;;
    "Edit script")
        FILE=$(ls ~/Scripts | dmenu -i -l 20)
        editi3 ~/Scripts/$FILE
    ;;
esac
