#!/bin/bash

DMENU="${DMENU:-dmenu}"

OPTION=$(echo '1. Select AWS profile
2. My Jiras
3. Copy Jira
4. Deploy
5. Config
6. Gif rec
7. Meme selector
8. ASCII ART
9. Gitmoji select
10. Edit script' \
    | $DMENU -i -l 10)

notify() {
    notify-send -a Script $1 -u normal
}

case $OPTION in
    "1. Select AWS profile")
        aws-select
    ;;
    "2. My Jiras")
        jira-select-mine
    ;;
    "3. Copy Jira")
        jira-dmenu \
            | xsel --clipboard --input
    ;;
    "4. Deploy")
        deploy ls \
            | $DMENU -p Deploy \
            | xargs -I {} deploy "{}" \
            | xargs -I {} notify-send -a Script "{}"
    ;;
    "5. Config")
        EDITOR=editi3 config $(config ls | $DMENU -i -l 10 -p Config)
    ;;
    "6. Gif rec")
        gifrec
    ;;
    "7. Meme selector")
        memesel
    ;;
    "8. ASCII ART")
        cat ~/Documents/ascii-art.txt \
            | $DMENU -l 10 -p ASCII \
            | tr -d '\n' \
            | ~/Scripts/copy
    ;;
    "9. Gitmoji select")
        gitmoji-menu
    ;;
    "10. Edit script")
        FILE=$(ls ~/Scripts | $DMENU -i -l 20 -p Script)
        editi3 ~/Scripts/$FILE
    ;;
esac
