#!/usr/bin/env bash
layout=$(setxkbmap -print | grep xkb_symbols | cut -d'+' -f 2)

if [ "$layout" = "us" ]; then
    other_layout="es"
else
    other_layout="us"
fi

setxkbmap -layout "$other_layout"
icon="$HOME/Pictures/icons/32x32/flags/$other_layout.png"
if [ ! -f "$icon" ]; then
    icon=/usr/share/icons/Papirus-Dark/16x16/devices/keyboard.svg
fi

notify-send \
    -r  1000 \
    -i $icon \
    -t 10000 \
    "Keyboard Layout" \
    "Switching to <b>${other_layout^^}</b>" \
