#!/usr/bin/bash

set -eo pipefail
task status:pending export \
    | jq -r '.[] | .uuid + "          " + (try (.tags|join(",")) catch "----") + "     " + .description' \
    | dmenu -l 10 \
    | cut -f1 -d' ' \
    | xargs taskopen
