#!/bin/bash

#OTHER_BROWSER='jumanji' # For instance /usr/bin/firefox
JIRA_BROWSER='firefox'
DEV_BROWSER='chromium'
AWS_BROWSER='brave'
BROWSER='zen-browser-optimized.desktop' # For instance /usr/bin/brave
BROWSER_OPTIONS='' # Optional, for command line options passed to browser
XDG_OPEN='/usr/bin/xdg-open'

#JIRA_PATTERN='^https\?:\/\/jira\.ravenpack\.com'
JIRA_SERVER_PATTERN='jira\.ravenpack\.com'
JIRA_CLOUD_PATTERN='ravenpack\.atlassian\.net'
JIRA_PATTERN='https\?:\/\/\('$JIRA_SERVER_PATTERN'\|'$JIRA_CLOUD_PATTERN'\)'
DEV_PATTERN='^.*\.bigdata.com\|^.*localhost:\|.*staging.ravenpack.com\|\.*app.ravenpack.com\|^\.*entitytool'
AWS_PATTERN='^https\?:\/\/.*\.console\.aws\.amazon\.com'
SLACK_PATTERN='^https://ravenpack.slack.com/archives/'

if echo "$1" | grep -q "$JIRA_PATTERN"; then
    open_qtile_group.py 7
    "$JIRA_BROWSER" $BROWSER_OPTIONS ${*}
    exit 0
elif echo "$1" | grep -q "$DEV_PATTERN"; then
    open_qtile_group.py 4
    "$DEV_BROWSER" $BROWSER_OPTIONS ${*}
    exit 0
elif echo "$1" | grep -q "$AWS_PATTERN"; then
    open_qtile_group.py 5
    "$AWS_BROWSER" $BROWSER_OPTIONS ${*}
    exit 0
elif echo "$1" | grep -q "$SLACK_PATTERN"; then
    # Change https://ravenpack.slack.com/archives/D024BGBMWD9/p1747129933157449?thread_ts=1747129933.157449&cid=D024BGBMWD9 to slack://channel?team=T0BNTHJPL&id=D024BGBMWD9&message=1747129933.157449&thread_ts=1747129933.157449&cid=D024BGBMWD9
    open_qtile_group.py 6
    ID=$(echo "$1" | grep -oP '(?<=archives/)[^/]+')
    MESSAGE=$(echo "$1" | grep -oP '(?<=/p)[^?]+')
    MESSAGE=$(echo "$MESSAGE" | sed 's/\([0-9]\{10\}\)\([0-9]\{6\}\)/\1.\2/')
    THREAD_TS=$(echo "$1" | grep -oP '(?<=thread_ts=)[^&]+')

    SLACK_URL="slack://channel?team=T0BNTHJPL&id=$ID"
    if [ -n "$MESSAGE" ]; then
        SLACK_URL="$SLACK_URL&message=$MESSAGE"
    fi
    if [ -n "$THREAD_TS" ]; then
        SLACK_URL="$SLACK_URL&thread_ts=$THREAD_TS"
    fi
    echo "Opening slack directly: $SLACK_URL"
    "$XDG_OPEN" "$SLACK_URL"
else
    # Calling always the browser cause errors when trying to open an application
    # "$NORMAL_BROWSER" $BROWSER_OPTIONS ${*}
    open_qtile_group.py 3
    "$XDG_OPEN" ${*}
    exit 0
fi
