#!/bin/bash

#OTHER_BROWSER='jumanji' # For instance /usr/bin/firefox
JIRA_BROWSER='firefox' # For instance /usr/bin/firefox
DEV_BROWSER='chromium' # For instance /usr/bin/chromium-browser
BROWSER='brave-browser.desktop' # For instance /usr/bin/brave
BROWSER_OPTIONS='' # Optional, for command line options passed to browser
XDG_OPEN='/usr/bin/xdg-open'

#JIRA_PATTERN='^https\?:\/\/jira\.ravenpack\.com'
JIRA_SERVER_PATTERN='jira\.ravenpack\.com'
JIRA_CLOUD_PATTERN='ravenpack\.atlassian\.net'
JIRA_PATTERN='https\?:\/\/\('$JIRA_SERVER_PATTERN'\|'$JIRA_CLOUD_PATTERN'\)'
DEV_PATTERN='^.*\.bigdata.com\|^.*localhost:\|.*staging.ravenpack.com\|\.*app.ravenpack.com\|^\.*entitytool'


if echo "$1" | grep -q "$JIRA_PATTERN"; then
    # i3-msg workspace '7: '
    open_qtile_group.py 7
    "$JIRA_BROWSER" $BROWSER_OPTIONS ${*}
    exit 0
elif echo "$1" | grep -q "$DEV_PATTERN"; then
    # i3-msg workspace '4: '
    open_qtile_group.py 4
    "$DEV_BROWSER" $BROWSER_OPTIONS ${*}
    exit 0
else
    # i3-msg workspace '3: '
    # Calling always the browser cause errors when trying to open an application
    # "$NORMAL_BROWSER" $BROWSER_OPTIONS ${*}
    open_qtile_group.py 3
    "$XDG_OPEN" ${*}
    exit 0
fi
