#!/bin/bash

#OTHER_BROWSER='jumanji' # For instance /usr/bin/firefox
JIRA_BROWSER='firefox'
DEV_BROWSER='chromium'
AWS_BROWSER='brave'
BROWSER='zen-browser-optimized.desktop' # For instance /usr/bin/brave
BROWSER_OPTIONS='' # Optional, for command line options passed to browser
XDG_OPEN='/usr/bin/xdg-open'
DEFAULT_REPO='https://gitlab.com/ravenpack/development/bigdata.com/backend'
CDK_REPO='https://gitlab.com/ravenpack/development/operations/cloud/rp-cdk'

#JIRA_PATTERN='^https\?:\/\/jira\.ravenpack\.com'
JIRA_SERVER_PATTERN='jira\.ravenpack\.com'
JIRA_CLOUD_PATTERN='ravenpack\.atlassian\.net'
JIRA_PATTERN='https\?://\('$JIRA_SERVER_PATTERN'\|'$JIRA_CLOUD_PATTERN'\)'
LATTICE_PATTERN='https\?://ravenpack.latticehq.com/'
DEV_PATTERN='^.*\.bigdata.com\|^.*localhost:\|.*staging.ravenpack.com\|\.*app.ravenpack.com\|^\.*entitytool'
AWS_PATTERN='^https\?://.*\.console\.aws\.amazon\.com\|^https://ravenpacksso.awsapps.com/'
SLACK_PATTERN='^https://ravenpack.slack.com/archives/'
GITLAB_MR_PATTERN='^\![0-9]\+'
CDK_GITLAB_MR_PATTERN='^\(CDK\|cdk\)\![0-9]\+'
JIRA_ID_PATTERN='^\(CPS\|TASE\|PX\|PLAT\|BIGDATA\)-[0-9]\+$'


if echo "$1" | grep -q "$JIRA_PATTERN"; then
    open_qtile_group.py 7
    "$JIRA_BROWSER" $BROWSER_OPTIONS ${*}
    exit 0
elif echo "$1" | grep -q "$LATTICE_PATTERN"; then
    open_qtile_group.py 7
    "$JIRA_BROWSER" $BROWSER_OPTIONS ${*}
    exit 0
elif echo "$1" | grep -q "$DEV_PATTERN"; then
    open_qtile_group.py 4
    "$DEV_BROWSER" $BROWSER_OPTIONS ${*}
    exit 0
elif echo "$1" | grep -q "$AWS_PATTERN"; then
    open_qtile_group.py 5
    "$AWS_BROWSER" $BROWSER_OPTIONS ${*}
    exit 0
elif echo "$1" | grep -q "$SLACK_PATTERN"; then
    # Change https://ravenpack.slack.com/archives/D024BGBMWD9/p1747129933157449?thread_ts=1747129933.157449&cid=D024BGBMWD9 to slack://channel?team=T0BNTHJPL&id=D024BGBMWD9&message=1747129933.157449&thread_ts=1747129933.157449&cid=D024BGBMWD9
    open_qtile_group.py 6
    ID=$(echo "$1" | grep -oP '(?<=archives/)[^/]+')
    MESSAGE=$(echo "$1" | grep -oP '(?<=/p)[^?]+')
    MESSAGE=$(echo "$MESSAGE" | sed 's/\([0-9]\{10\}\)\([0-9]\{6\}\)/\1.\2/')
    THREAD_TS=$(echo "$1" | grep -oP '(?<=thread_ts=)[^&]+')

    SLACK_URL="slack://channel?team=T0BNTHJPL&id=$ID"
    if [ -n "$MESSAGE" ]; then
        SLACK_URL="$SLACK_URL&message=$MESSAGE"
    fi
    if [ -n "$THREAD_TS" ]; then
        SLACK_URL="$SLACK_URL&thread_ts=$THREAD_TS"
    fi
    echo "Opening slack directly: $SLACK_URL"
    "$XDG_OPEN" "$SLACK_URL"
elif echo "$1" | grep -q "$GITLAB_MR_PATTERN"; then
    open_qtile_group.py 3
    MR_NUMBER=$(echo "$1" | grep -oP '(?<=\!)[0-9]+')
    GITLAB_URL="$DEFAULT_REPO/-/merge_requests/$MR_NUMBER"
    "$XDG_OPEN" $BROWSER_OPTIONS "$GITLAB_URL"
    exit 0
elif echo "$1" | grep -q "$CDK_GITLAB_MR_PATTERN"; then
    open_qtile_group.py 3
    # Find the MR number after "CDK!" or "cdk!"
    MR_NUMBER=$(echo "CDK!493" | grep -oP '(CDK|cdk)!\K[0-9]+')
    echo "$MR_NUMBER" > /tmp/last_cdk_mr_number.txt
    GITLAB_URL="$CDK_REPO/-/merge_requests/$MR_NUMBER"
    "$XDG_OPEN" $BROWSER_OPTIONS "$GITLAB_URL"
    exit 0
elif echo "$1" | grep -q "$JIRA_ID_PATTERN"; then
    open_qtile_group.py 7
    JIRA_ID=$1
    JIRA_URL="https://ravenpack.atlassian.net/browse/$JIRA_ID"
    "$JIRA_BROWSER" $BROWSER_OPTIONS "$JIRA_URL"
    exit 0
else
    # Calling always the browser cause errors when trying to open an application
    # "$NORMAL_BROWSER" $BROWSER_OPTIONS ${*}
    open_qtile_group.py 3
    "$XDG_OPEN" ${*}
    exit 0
fi
